title: Guillaume Moigneu - nls.io
author:
  name: Guillaume Moigneu
  email: 'guillaume@moigneu.net'
  page: /guillaume-moigneu
metadata:
    description: 'Random thoughts about eCommerce & Magento, Symfony2, privacy & sysadmin.'

